### ISSUE TITLE
When playing a video, which is not fully 360.

### ISSUE THREAD

**Issue by ghost** [innovationmauritiustelecom/video_player_360#12]
When playing any video which doesn't have 360 view, it's showing a black screen instead of constraining the video view to a specific size.
Like this video, [Travel](https://youtu.be/9kRz8AnEySU).
Just restrict the video movement, when it's not fully 360.

**Comment by stephangopaul** [comment]
Hello @shaan-saz, sorry for missing your issue. 
Please note that this plugin requires a 360 video url.
