### ISSUE TITLE
pod install

### ISSUE THREAD

**Issue by kazumasamatsumoto** [innovationmauritiustelecom/video_player_360#13]
(base) video360% flutter --version
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (10 days ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
(base) video360% flutter run
Multiple devices found:
Android SDK built for x86 (mobile)  • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
iPhone SE (2nd generation) (mobile) • BCDBC40C-35B0-42ED-A7DC-5D1BACA7E33A • ios         •
com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
[0]: Android SDK built for x86 (emulator-5554)
[1]: iPhone SE (2nd generation) (BCDBC40C-35B0-42ED-A7DC-5D1BACA7E33A)
Please choose one: [0|1]: 1
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Running pod install...                                              2.0s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `video_player_360` from `.symlinks/plugins/video_player_360/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_7_3_e.txt exists! Returning local because checking is only perfomed in repo
      update
      CDN: trunk Relative path: Specs/7/3/e/GVRKit/1.170.0/GVRKit.podspec.json exists! Returning local because checking is only
      perfomed in repo update
      CDN: trunk Relative path: Specs/7/3/e/GVRKit/1.170.0/GVRKit.podspec.json exists! Returning local because checking is only
      perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_3_7_9.txt exists! Returning local because checking is only perfomed in repo
      update
      CDN: trunk Relative path: Specs/3/7/9/GVRSDK/1.170.0/GVRSDK.podspec.json exists! Returning local because checking is only
      perfomed in repo update
      CDN: trunk Relative path: Specs/3/7/9/GVRSDK/1.170.0/GVRSDK.podspec.json exists! Returning local because checking is only
      perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_c_e_3.txt exists! Returning local because checking is only perfomed in repo
      update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.4.0/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.0/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.1/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.2/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.3/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.4/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.5/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.6/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.7/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.8/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.9/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.10/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.11/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.12/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.13/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.14/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.1.15/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.2.0/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.2.1/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.2.2/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.3.0/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.3.1/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/e/3/GTMSessionFetcher/1.4.0/GTMSessionFetcher.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_7_4_b.txt exists! Returning local because checking is only perfomed in repo
      update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.2.2/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.0/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.1/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.2/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.3/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.1.4/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.2.0/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.2.1/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.2.2/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/4/b/GoogleToolboxForMac/2.2.2/GoogleToolboxForMac.podspec.json exists! Returning local
      because checking is only perfomed in repo update

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A GTMSessionFetcher
      A GVRKit
      A GVRSDK
      A GoogleToolboxForMac
      A video_player_360

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing GTMSessionFetcher (1.4.0)
      > Copying GTMSessionFetcher from
      `/Users/matsumotoisshou/Library/Caches/CocoaPods/Pods/Release/GTMSessionFetcher/1.4.0-6f5c8` to `Pods/GTMSessionFetcher`

    -> Installing GVRKit (1.170.0)
      > Copying GVRKit from `/Users/matsumotoisshou/Library/Caches/CocoaPods/Pods/Release/GVRKit/1.170.0-5c3c4` to
      `Pods/GVRKit`

    -> Installing GVRSDK (1.170.0)
      > Copying GVRSDK from `/Users/matsumotoisshou/Library/Caches/CocoaPods/Pods/Release/GVRSDK/1.170.0-690e9` to
      `Pods/GVRSDK`

    -> Installing GoogleToolboxForMac (2.2.2)
      > Copying GoogleToolboxForMac from
      `/Users/matsumotoisshou/Library/Caches/CocoaPods/Pods/Release/GoogleToolboxForMac/2.2.2-80064` to
      `Pods/GoogleToolboxForMac`

    -> Installing video_player_360 (0.0.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries:
    (/Users/matsumotoisshou/flutter-app/video360/ios/Pods/GVRKit/Frameworks/GVRKit.framework)

    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_
    validator.rb:84:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_
    validator.rb:74:in `each_key'
    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_
    validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_
    validator.rb:73:in `each'
    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_
    validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_
    validator.rb:38:in `validate!'
    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:590:in
    `validate_targets'
    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:158:in
    `install!'
    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:i
    n `run'
    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Users/matsumotoisshou/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone SE (2nd generation).
(base) video360%

**Comment by theLastOrbit** [comment]
I have the same error. does anyone have any solutions please?

**Comment by stephangopaul** [comment]
@md-rubel please note that this plugin can only be added in flutter projects generated with the flag -i objc. In other words, it is not compatible with swift.
