### ISSUE TITLE
videos except vr360 not working

### ISSUE THREAD

**Issue by SagarDhiman018** [innovationmauritiustelecom/video_player_360#14]
is it work with normal video or vr180? it showing only black screen when i trying to play other videos url except vr360.
please clarify or mention this thing in read me.Thanks.

it is showing this error in console log:

D/MediaPlayerNative(17759): Message: MEDIA_ERROR(100), ext1=MEDIA_ERROR_UNKNOWN(1), ext2=0x80000000
E/MediaPlayerNative(17759): error (1, -2147483648)
D/MediaPlayer(17759): create failed:
D/MediaPlayer(17759): java.io.IOException: Prepare failed.: status=0x1
D/MediaPlayer(17759): 	at android.media.MediaPlayer._prepare(Native Method)
D/MediaPlayer(17759): 	at android.media.MediaPlayer.prepare(MediaPlayer.java:1427)
D/MediaPlayer(17759): 	at android.media.MediaPlayer.create(MediaPlayer.java:965)
D/MediaPlayer(17759): 	at android.media.MediaPlayer.create(MediaPlayer.java:938)
D/MediaPlayer(17759): 	at android.media.MediaPlayer.create(MediaPlayer.java:917)
D/MediaPlayer(17759): 	at com.example.video_player_360.videoplayer.MediaLoader$MediaLoaderTask.doInBackground(MediaLoader.java:200)
D/MediaPlayer(17759): 	at com.example.video_player_360.videoplayer.MediaLoader$MediaLoaderTask.doInBackground(MediaLoader.java:147)
D/MediaPlayer(17759): 	at android.os.AsyncTask$2.call(AsyncTask.java:334)
D/MediaPlayer(17759): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
D/MediaPlayer(17759): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
D/MediaPlayer(17759): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
D/MediaPlayer(17759): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
D/MediaPlayer(17759): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D/MediaPlayer(17759): 	at java.lang.Thread.run(Thread.java:784)

**Comment by stephangopaul** [comment]
Hello @sagar440, please note that this plugin works only with 360 videos. Thank you
