### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

### ISSUE THREAD

**Issue by FromJeju** [innovationmauritiustelecom/video_player_360#15]
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

grep -R UIWebView
Binary file ios/Pods/GVRSDK/Libraries/libGVRSDK.a matches

Could you update to WKWebView?

**Comment by stephangopaul** [comment]
Hi @FromJeju, 
The issue is in the GVRSDK library; which is out of our control. 
Since Google has [deprecated this library](https://github.com/googlevr/gvr-ios-sdk), we will need to [migrate to the new SDK](https://developers.google.com/cardboard).

Pull requests are more than welcomed. :)
