### ISSUE TITLE
Return a widget

### ISSUE THREAD

**Issue by rlazom** [innovationmauritiustelecom/video_player_360#17]
This could be the idea:

Return a widget so in flutter could be handle the interface (custom UI), buttons and interaction
Maybe could also provide an API to interact with specific actions, such as: play, pause, video dimension, etc.

**Comment by stephangopaul** [comment]
Hello @rlazom,

Nice idea! Due to time limitation, we will not be able to implement this feature. However, pull requests are more than welcomed! 😊
