### ISSUE TITLE
info/warning when playing the video

### ISSUE THREAD

**Issue by maxTeste** [innovationmauritiustelecom/video_player_360#18]
i'm playing a video 360 on my app and wonder if the video has a maximum space limit if i try with this one: https://github.com/stephangopaul/video_samples/blob/master/gb.mp4?raw=true 

work good, but if i try with one 360MB it give me warnings:
it's because the video is to big?

D/HostConnection( 5794): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/HostConnection( 5794): HostConnection::get() New Host Connection established 0xd6e40f90, tid 12091
D/HostConnection( 5794): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
W/MediaPlayerNative( 5794): info/warning (703, 5146)
W/MediaPlayerNative( 5794): info/warning (701, 0)
W/MediaPlayerNative( 5794): info/warning (703, 3915)
W/MediaPlayerNative( 5794): info/warning (702, 0)
W/MediaPlayerNative( 5794): info/warning (703, 8788)
W/MediaPlayerNative( 5794): info/warning (701, 0)
W/MediaPlayerNative( 5794): info/warning (703, 5011)
W/MediaPlayerNative( 5794): info/warning (702, 0)
W/MediaPlayerNative( 5794): info/warning (703, 8925)
W/MediaPlayerNative( 5794): info/warning (701, 0)

**Comment by stephangopaul** [comment]
Hi @rubenteste,

Yes, maybe the video is too big. Try reducing the resolution; or hosting and streaming the video.

**Comment by maxTeste** [comment]
i tried with one video, that is hosted in a server, that have 360MB and when I played the video it wasn't smooth, and sometimes it stopped. do u know the maximum size that the plugin suport? if i try to reduce the resolution of the video even more, will get even worse quality
