### ISSUE TITLE
I get this error when debugging ios. How can I fix it??

### ISSUE THREAD

**Issue by leegiseong20030603** [innovationmauritiustelecom/video_player_360#19]
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/leegiseong/Documents/Flutter Project/Hagwonui Munhwa/hagwonuimunhwa/ios/Pods/GVRKit/Frameworks/GVRKit.framework)

I get this error when debugging ios. How can I fix it??

**Comment by stephangopaul** [comment]
This seems linked to an issue with flutter.
https://stackoverflow.com/questions/50306019/flutter-cocoapods-the-pods-runner-target-has-transitive-dependencies-that-inc

**Comment by leegiseong20030603** [comment]
@stephangopaul 
Thanks for any help in solving my problem. But I use_frameworks! Commenting out will cause problems with other packages, resulting in errors like this.

Xcode's output:
↳
    webview_flutter-erpxzwtuwdritvhfslsvlwebvrlq
    /Users/leegiseong/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/kakao_flutter_sdk-0.5.4/ios/Classes/KakaoFlutterSdkPlugin.m:4:17: error: definition of 'KakaoFlutterSdkPlugin' must be imported from module 'kakao_flutter_sdk.KakaoFlutterSdkPlugin' before it is required
    @implementation KakaoFlutterSdkPlugin
                    ^
    In module 'kakao_flutter_sdk' imported from /Users/leegiseong/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/kakao_flutter_sdk-0.5.4/ios/Classes/KakaoFlutterSdkPlugin.m:2:
    /Users/leegiseong/Documents/Flutter Project/Hagwonui Munhwa/hagwonuimunhwa/build/ios/Debug-iphoneos/kakao_flutter_sdk/kakao_flutter_sdk.framework/Headers/KakaoFlutterSdkPlugin.h:3:12: note: previous definition is here
    @interface KakaoFlutterSdkPlugin : NSObject<FlutterPlugin>
               ^
    1 error generated.
    webview_flutter-erpxzwtuwdritvhfslsvlwebvrlq
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on iPhone.
