### ISSUE TITLE
Vr video player with control

### ISSUE THREAD

**Issue by gausoft** [innovationmauritiustelecom/video_player_360#2]
Thanks for your work!.
How can we use this package to build vr app?
Could you add local video playing support?

**Comment by stephangopaul** [comment]
Hi @Gausoft 
This is a flutter plugin. You need to add `video_player_360: ^0.0.9 in your pubspec.yaml dependencies.` to use it. 
We plan to support local video playing later but you can do a pull request to add same feature. 
Thank you.

**Comment by gausoft** [comment]
Ok thanks
