### ISSUE TITLE
Can't play after click button

### ISSUE THREAD

**Issue by anhthiet92buh** [innovationmauritiustelecom/video_player_360#23]
Hepl me! I can play in emulator android sdk 33.
this is error:

Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method playvideo on channel innov.lab/video_player_360))
in the line of code: await VideoPlayer360.playVideoUrl('https://github.com/stephangopaul/video_samples/blob/master/gb.mp4?raw=true');

**Comment by stephangopaul** [comment]
Dear @anhthiet92buh,

This library is deprecated.

We don't recommend using same.

Regards,
