### ISSUE TITLE
force cardboard

### ISSUE THREAD

**Issue by sopaidar** [innovationmauritiustelecom/video_player_360#8]
Hi
grate work. how we can add cardboard key or force to play in cardboard?
and does it support hls? because I couldn't play hls 360 video.

**Comment by stephangopaul** [comment]
Hi @sopaidar,
The cardboard key is disabled on this version. We plan to add it at a later stage.
However, pull requests are welcomed 
^^.

**Comment by sopaidar** [comment]
Thanks. I would be happy to try help you.
And the second question. Do you know it support hls or not? I tried and it doesn't work.

**Comment by stephangopaul** [comment]
Yes the Google VR SDK for iOS and Android both support the cardboard. We intentionally disabled it in the flutter library.

**Comment by nickrivers** [comment]
Thanks for the plugin :)

Any update for the Cardboard feature?

**Comment by stephangopaul** [comment]
@nickrivers not yet. Pull requests are welcomed though. :)
